name: skeleton application

run-name: "Build and push staging image"

on:
  push:
    # branches:
    #   - gha-testing

env:
  DEPLOY_ENV_NAME: staging
  DEPLOY_SVC_NAME: frontend_nginx
  IMAGE_REPO: 5878376574849.dkr.ecr.eu-west-1.amazonaws.com/futrli/skeleton-application-frontend
  SERVICE_NAME: skeleton-application

jobs:
  build-staging: # job name
    runs-on: ubuntu-latest
      # group: big-runners # big runners group
      # or run on runner group  labeled
      # labels: ubuntu-20.04-16core
    steps:  
    # build tag and push image
      - name: checkout code
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: v0.11.2

      # ECR
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build and push
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     platforms: linux/amd64
      #     push: true
      #     tags: user/app:latest